server:
  port: 8081
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
canal.conf:
  srcDataSources:
    defaultDS:
      diver: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/canal_manager?useUnicode=true
      username: root
      password: root
  mode: rabbitMQ
  flatMessage: true
  zookeeperHosts:
  syncBatchSize: 5000
  retries: 0
  timeout:
  accessKey:
  secretKey:
  consumerProperties:
    rabbitmq.host: me:5672
    rabbitmq.virtual.host: /
    rabbitmq.username: redamancy
    rabbitmq.password: redamancy
  canalAdapters:
    - instance: canal
      groups:
        - groupId: canal.key
          outerAdapters:
            - name: rdb
              key: mysql1
              properties:
                jdbc.driverClassName: ru.yandex.clickhouse.ClickHouseDriver
                jdbc.url: jdbc:clickhouse://me:8123
                jdbc.username: default
                jdbc.password:

